name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [v1.0, v1.1, v1.2.0, latest]
        flags: [
          DUMMY_LIBC_INIT=1, 
          DUMMY_TIMEZONE=1, 
          KERNEL_NOPATCH=1, 
          NEWLIB_NANO=1, 
          KERNEL_NOPATCH=1 NEWLIB_NANO=1,
          KERNEL_NOPATCH=1 NEWLIB_NANO=1 DUMMY_LIBC_INIT=1,
          KERNEL_NOPATCH=1 NEWLIB_NANO=1 DUMMY_TIMEZONE=1,  
          DEFAULT=1
          ]

    container: ps2dev/ps2dev:${{ matrix.docker_tag }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base
    
    - name: Compile project
      run: |
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN) all ${{ matrix.flags }}

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ steps.slug.outputs.sha8 }}-${{matrix.docker_tag}}-${{ matrix.flags }}
        path: hello.elf
